### ISSUE TITLE
发送异常报错

### ISSUE THREAD

**Issue by dwyao** [bookfere/Send-to-Kindle-Calibre-Plugin#6]
cailibe用插件发送失败，直接邮箱发送没有问题。失败log如下，是否因为版本不支持？

calibre, version 7.3.0 (win32, embedded-python: True)
通过邮件发送书籍失败: 失败: Email 英语常用词疑难用法手册 to davidweb123@kindle.com

Starting job: Email 英语常用词疑难用法手册 to davidweb123@kindle.com 

Sending failed...
 
Traceback (most recent call last):
  File "calibre\gui2\email.py", line 48, in run
  File "calibre\gui2\email.py", line 137, in sendmail
  File "calibre\utils\smtp.py", line 163, in sendmail
  File "calibre\utils\smtp.py", line 143, in sendmail_direct
OSError: Failed to send mail: SMTPRecipientsRefused({'davidweb123@kindle.com': (550, b'5.7.1 IP address blacklisted by recipient')})
 

Retrying in 1 seconds...
 
Waiting 1 seconds before sending, to avoid being marked as spam.
You can control this delay via Preferences->Tweaks 

Sending failed...
 
Traceback (most recent call last):
  File "calibre\gui2\email.py", line 48, in run
  File "calibre\gui2\email.py", line 137, in sendmail
  File "calibre\utils\smtp.py", line 163, in sendmail
  File "calibre\utils\smtp.py", line 143, in sendmail_direct
OSError: Failed to send mail: SMTPRecipientsRefused({'davidweb123@kindle.com': (550, b'5.7.1 IP address blacklisted by recipient')})
 
Job: "Email 英语常用词疑难用法手册 to davidweb123@kindle.com" failed with error: 
Traceback (most recent call last):
  File "calibre\gui2\threaded_jobs.py", line 82, in start_work
  File "calibre\gui2\email.py", line 105, in __call__
  File "calibre\gui2\email.py", line 48, in run
  File "calibre\gui2\email.py", line 137, in sendmail
  File "calibre\utils\smtp.py", line 163, in sendmail
  File "calibre\utils\smtp.py", line 143, in sendmail_direct
OSError: Failed to send mail: SMTPRecipientsRefused({'davidweb123@kindle.com': (550, b'5.7.1 IP address blacklisted by recipient')})
 
Called with args: ('C:\\Users\\PC-WORK\\AppData\\Local\\Temp\\calibre_9h4m812z\\1o_8inuxcaltmpfmt.epub', '英语常用词疑难用法手册.epub', 'davidweb123@kindle.com', '电子书： 英语常用词疑难用法手册', '已添加, 你可以找到电子书\n\n英语常用词疑难用法手册\n\t由 陈用仪\n\n使用 EPUB 格式.') {'notifications': <queue.Queue object at 0x000001F81262B950>, 'abort': <threading.Event at 0x1f81262aa10: unset>, 'log': <calibre.utils.logging.GUILog object at 0x000001F81266D410>}

**Comment by bookfere** [comment]
这是个和 SMTP 相关的错误，和插件没有直接关联。从错误信息看，原因是发送邮件的 IP 地址被接收方列为黑名单：

> 550, b'5.7.1 IP address blacklisted by recipient')

如果你没有使用邮箱服务商提供的 SMTP，建议根据邮箱服务商提供的 SMTP 信息正确设置 SMTP 服务器。如果你使用的是邮箱服务商提供的 SMTP，可以换其他邮箱服务商试试看。
